parameters:
    fra_casula_stream_wrapper_sandbox: '\FraCasula\Bundle\PhpSandboxBundle\Stream\SandboxStream'

services:
    fra_casula_php_sandbox:
        class: FraCasula\Bundle\PhpSandboxBundle\Services\PhpSandbox
        arguments:
            - %fra_casula_stream_wrapper_sandbox%