language: php

sudo: false

cache:
    directory:
        - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
    - vendor/bin/phpunit